# Site settings
title: codevloper
tagline: "cacatan interaksi manusia dan/dengan/atau/tanpa komputer"
url: "http://codevloper.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /assets/site/social.jpg # be sure to change this image
facebook: codevloper
twitter: codevloper
github: codevloper
googleplus: codevloper
instagram: codevloper

# Contact
phone: "916-276-1044" # This is my real number. You should text me.
email: "hello@codevloper.io" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

permalink:   /:categories/:title.html